### ISSUE TITLE
Verifying the workflow to EnergyPlus v8.3

### ISSUE THREAD

**Issue by howardcheung** [NREL/OpenStudio-fault-measure-gem#2]
The current Measure AutoSizeToHardSizeEPlusVersion is only applicable to the seed models in this repository only for EnergyPlus version 8.1 and 8.2. Its applicability to EnergyPlus version 8.3 with the current seed model needs verification.

**Comment by howardcheung** [comment]
Branch AutoSizingCheckfor8.3 opened to initiate the verification.

**Comment by JanghyunJK** [comment]
prob correct to close this issue. but thanks for the earlier effort @howardcheung !!
